### ISSUE TITLE
Request calculation logics on previous Fuze SDK

### ISSUE THREAD

**Issue by 0xhipo** [zetamarkets/zeta-abi#1]
Hi Zeta taem,

Would be great if ABI could ship with calculations of accounts and oracles. These calculations are among the core logics of Zeta Markets, so I'd suggest they are maintained here instead of 3rd party programs.

We are trying to use the new ABI package and find these methods missing from previous dependency:
```
1. MarginAccount.get_initial_margin()
2. MarginAccount.get_maintenance_margin()
3. MarginAccount.get_unrealized_pnl()
```

**Comment by xjcaa** [comment]
Should be resolved in #2
